env:
  browser: true
  es2021: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  no-console: 0
  import/extensions:
  import/prefer-default-export: off,
  - error
  - ignorePackages
  - js: always
  import/extensions: 0
}